
ALTER TABLE dbo.SUBE_Venta ADD CONSTRAINT
	PK_SUBE_Venta PRIMARY KEY CLUSTERED 
	(
	ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.SUBE_Venta SET (LOCK_ESCALATION = TABLE)
GO


ALTER TABLE dbo.GUIATBA_TipoTransporte ADD CONSTRAINT
	PK_GUIATBA_TipoTransporte PRIMARY KEY CLUSTERED 
	(
	ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.GUIATBA_TipoTransporte SET (LOCK_ESCALATION = TABLE)
GO


ALTER TABLE dbo.GUIATBA_Transporte ADD CONSTRAINT
	PK_GUIATBA_Transporte PRIMARY KEY CLUSTERED 
	(
	ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.GUIATBA_Transporte SET (LOCK_ESCALATION = TABLE)
GO


ALTER TABLE dbo.GUIATBA_TransporteIntersecciones ADD CONSTRAINT
	PK_GUIATBA_TransporteIntersecciones PRIMARY KEY CLUSTERED 
	(
	CodigoO,
	CodigoD
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.GUIATBA_TransporteIntersecciones SET (LOCK_ESCALATION = TABLE)
GO